import { SelectModel } from "../models";

export const COUNTRY: SelectModel[] = [
  { id: 'Argentina', value: 'ar' },
  { id: 'Australia', value: 'au' },
  { id: 'Austria', value: 'at' },
  { id: 'Belgium', value: 'be' },
  { id: 'Brazil', value: 'br' },
  { id: 'Bulgaria', value: 'bg' },
  { id: 'Canada', value: 'ca' },
  { id: 'China', value: 'cn' },
  { id: 'Colombia', value: 'co' },
  { id: 'Cuba', value: 'cu' },
  { id: 'Czech republic', value: 'cz' },
  { id: 'Egypt', value: 'eg' },
  { id: 'France', value: 'fr' },
  { id: 'Germany', value: 'de' },
  { id: 'Greece', value: 'gr' },
  { id: 'Hong kong', value: 'hk' },
  { id: 'Hungary', value: 'hu' },
  { id: 'India', value: 'in' },
  { id: 'Indonesia', value: 'id' },
  { id: 'Ireland', value: 'ie' },
  { id: 'Israel', value: 'il' },
  { id: 'Italy', value: 'it' },
  { id: 'Japan', value: 'jp' },
  { id: 'Latvia', value: 'lv' },
  { id: 'Lebanon', value: 'lb' },
  { id: 'Lithuania', value: 'lt' },
  { id: 'Malaysia', value: 'my' },
  { id: 'Mexico', value: 'mx' },
  { id: 'Morocco', value: 'ma' },
  { id: 'Netherland', value: 'nl' },
  { id: 'New zealand', value: 'nz' },
  { id: 'Nigeria', value: 'ng' },
  { id: 'North korea', value: 'kp' },
  { id: 'Norway', value: 'no' },
  { id: 'Pakistan', value: 'pk' },
  { id: 'Philippines', value: 'ph' },
  { id: 'Poland', value: 'pl' },
  { id: 'Portugal', value: 'pt' },
  { id: 'Romania', value: 'ro' },
  { id: 'Russia', value: 'ru' },
  { id: 'Saudi arabia', value: 'sa' },
  { id: 'Serbia', value: 'rs' },
  { id: 'Singapore', value: 'sg' },
  { id: 'Slovakia', value: 'sk' },
  { id: 'Slovenia', value: 'si' },
  { id: 'South africa', value: 'za' },
  { id: 'South korea', value: 'kr' },
  { id: 'Spain', value: 'es' },
  { id: 'Sweden', value: 'se' },
  { id: 'Switzerland', value: 'ch' },
  { id: 'Taiwan', value: 'tw' },
  { id: 'Thailand', value: 'th' },
  { id: 'Turkey', value: 'tr' },
  { id: 'Ukraine', value: 'ua' },
  { id: 'United arab emirates', value: 'ae' },
  { id: 'United kingdom', value: 'gb' },
  { id: 'United states of america', value: 'us' },
  { id: 'Venezuela', value: 've' },
];

export const DEFAULT_COUNTRY = 'us'
