import { SelectModel } from '../models';

export const LANGUAGE: SelectModel[] = [
  { id: 'Arabic', value: 'ar' },
  { id: 'Bosnian', value: 'bs' },
  { id: 'Bulgarian', value: 'bg' },
  { id: 'Chinese', value: 'zh' },
  { id: 'Croatian', value: 'hr' },
  { id: 'Czech', value: 'cs' },
  { id: 'Dutch', value: 'nl' },
  { id: 'English', value: 'en' },
  { id: 'French', value: 'fr' },
  { id: 'German', value: 'de' },
  { id: 'Greek', value: 'el' },
  { id: 'Hebrew', value: 'he' },
  { id: 'Hindi', value: 'hi' },
  { id: 'Hungarian', value: 'hu' },
  { id: 'Indonesian', value: 'in' },
  { id: 'Italian', value: 'it' },
  { id: 'Japanese', value: 'jp' },
  { id: 'Korean', value: 'ko' },
  { id: 'Latvian', value: 'lv' },
  { id: 'Lithuanian', value: 'lt' },
  { id: 'Malay', value: 'ms' },
  { id: 'Norwegian', value: 'no' },
  { id: 'Polish', value: 'pl' },
  { id: 'Portuguese', value: 'pt' },
  { id: 'Romanian', value: 'ro' },
  { id: 'Russian', value: 'ru' },
  { id: 'Serbian', value: 'sr' },
  { id: 'Slovak', value: 'sk' },
  { id: 'Slovenian', value: 'sl' },
  { id: 'Spanish', value: 'es' },
  { id: 'Swedish', value: 'sv' },
  { id: 'Thai', value: 'th' },
  { id: 'Turkish', value: 'tr' },
  { id: 'Ukrainian', value: 'uk' },
];

export const DEFAULT_LANGUAGE = 'en'
